### ISSUE TITLE
secret.yml have no "apiVersion" key?

### ISSUE THREAD

**Issue by SDLyu** [Landoop/kafka-helm-charts#17]
It would failed when run command `helm install` if no `apiVersion`.

```
Kubectl apply failed. Error: error: error validating "/tmp/app-template891208987": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false : exit status 1
```

**Comment by andrewstevenson** [comment]
@SDLyu Which chart? I'll update the charts.

**Comment by andrewstevenson** [comment]
@SDLyu I've correct them, let use know how you get on, strangely Helm init and template is ok.

**Comment by SDLyu** [comment]
Hi @andrewstevenson 
There are some typos, and I open #18 to correct them.

**Comment by SDLyu** [comment]
BTW, I can't pull image from repository `registry.hub.docker.com/datamountaineer/kafka-connect-elastic5`, but change repository to `datamountaineer/kafka-connect-elastic5` is ok.

**Comment by andrewstevenson** [comment]
@SDLyu  ok, updating the rest now. Thanks!

**Comment by SDLyu** [comment]
Hi @andrewstevenson 
It seems that need to run command `bash package.sh` to update charts, because helm still install old charts.
Thanks

**Comment by andrewstevenson** [comment]
@SDLyu I've run the script and pushed.
