### ISSUE TITLE
Elastic6 sink broken chart

### ISSUE THREAD

**Issue by burdiyan** [Landoop/kafka-helm-charts#20]
Helm chart for elastic6-sink seems to be broken.

There's repeated value in `values.yaml` file for `clusterName` saying first that is the name of the consumer group, and then it says it's the name of elastic search cluster.

On the other hand image `datamountaineer/kafka-connect-elastic6:1.2.0` which is the default value does not exist.

**Comment by andrewstevenson** [comment]
@burdiyan Thanks for the report. The image defaults are wrong. You can override with the ``--set`` flag. The duplicate cluster name is a bug. I'll fix shortly.

**Comment by andrewstevenson** [comment]
@burdiyan try now.

**Comment by burdiyan** [comment]
@andrewstevenson That was fast :) Thanks, will try it soon and let you know.

**Comment by burdiyan** [comment]
Now my problem seems to be that connect tries to create a topic for storing offsets with replication factor of 3, but I'm testing that on a cluster with 1 broker. There seems to be no way to change that through the Helm values.

**Comment by andrewstevenson** [comment]
@burdiyan We'll have to add this to the `CONNECT_` variables. I can do it later on today. You can pre create the topics while I update the charts.

> # The following properties set the replication factor for the three internal topics, defaulting to 3 for each
> # and therefore requiring a minimum of 3 brokers in the cluster. Since we want the examples to run with
> # only a single broker, we set the replication factor here to just 1. That's okay for the examples, but
> # ALWAYS use a replication factor of AT LEAST 3 for production environments to reduce the risk of
> # losing connector offsets, configurations, and status.
> config.storage.replication.factor=1
> offset.storage.replication.factor=1
> status.storage.replication.factor=1
> 
> # The config storage topic must have a single partition, and this cannot be changed via properties.
> # Offsets for all connectors and tasks are written quite frequently and therefore the offset topic
> # should be highly partitioned; by default it is created with 25 partitions, but adjust accordingly
> # with the number of connector tasks deployed to a distributed worker cluster. Kafka Connect records
> # the status less frequently, and so by default the topic is created with 5 partitions.
> #offset.storage.partitions=25
> #status.storage.partitions=5

**Comment by Antwnis** [comment]
@burdiyan 

Alex, https://github.com/Landoop/kafka-helm-charts/pull/21 now addresses this issue with the replication factor - and charts are now configurable

I'm closing this issue. 

Also let us know regarding Go/Avro client lib suggestions
