### ISSUE TITLE
Can not read the license file:/data/license.json

### ISSUE THREAD

**Issue by shootkin** [Landoop/kafka-helm-charts#23]
Hi! i'm trying to install lenses helm chart with command:

`helm install lenses --name lenses --namespace lenses -f lenses/config.yml`

lenses/config.yml contains such block:

```
lenses:
  license: |
    This
    is
    a
    license

```
All seems to be OK, but after "helm install" command I see such errors in pod's logs:

2018-07-10 11:23:16,869 ERROR [c.l.k.l.Main$:156] Can not read the license file:/data/license.json
2018-07-10 11:23:16,870 ERROR [c.l.k.l.Main$:157] Lenses will shutdown.

So what's wrong with my license?

**Comment by andrewstevenson** [comment]
The chart will create a secret with the license inside, can you check it's be populated correctly?

**Comment by andrewstevenson** [comment]
also check you are on version 1.0.8 of the chart.

**Comment by shootkin** [comment]
Thank you for reply. I populated license to lenses/config.yml incorrectly ( I passed only key instead of whole json license ). 
For now it works
