### ISSUE TITLE
Cannot login to fresh installation

### ISSUE THREAD

**Issue by shootkin** [Landoop/kafka-helm-charts#24]
Hi! I just deployed lenses with helm. I didn't change default username/password, so they should be admin/admin, as it is described in lenses documentation. But when I try to login with admin/admin I see such error: "Could not login". If I go to browser developer's console, I see this messages:

Failed at method [POST] [lenses/api/login] with error: 
{"data":{"success":false,"token":null,"user":null,"schemaRegistryDelete":true},"status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/login","data":{"user":"admin","password":"*******"},"dataType":"json","headers":{"Content-Type":"application/json","Accept":"application/json, text/plain"}},"statusText":"Unauthorized"}

vendor.689882bfec3849ba2cda.bundle.js:1 Failed at method [GET] [lenses/api/user/profile] with error: 
{"data":"CredentialsMissing","status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/user/profile","dataType":"json","headers":{"Accept":"application/json, text/plain"}},"statusText":"Unauthorized"}

So what are the default login/password for fresh lenses installation?

**Comment by chdask** [comment]
Hi @shootkin you need to set the users on values.yaml 

Check here
http://lenses.stream/install_setup/kubernetes/index.html#helm-sec-users

**Comment by shootkin** [comment]
Thank you for reply! I uncommented this block in values.yml and upgraded release, but  I still cannot login.

Command “kubectl get secret lenses -o jsonpath --template '{.data.users}' --namespace=lenses | base64 –d”

shows such output: 

[
  {
      "username": "admin",
      "displayname": "LensesAdmin",
      "password": "admin",
      "groups":["adminGroup"]
  }
]

So what’s wrong with my helm config?

**Comment by shootkin** [comment]
For me it helped to patch deployment in order to use new secret:

kubectl patch deployment lenses -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}" --namespace=lenses
