### ISSUE TITLE
helm install lenses fails

### ISSUE THREAD

**Issue by sundipnair** [Landoop/kafka-helm-charts#35]
I am running a AKS (Azure) cluster.

Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Helm version

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

I have run

helm repo add landoop https://landoop.github.io/kafka-helm-charts/

and

helm repo update.

This succeeds.

But when I run 

helm install lenses --name lenses --namespace lenses

I get he following error 

Error: release lenses failed: the server could not find the requested resource

I have cloned the git repo locally and run the charts form my machine. Still same result.

Could you please send me some pointers why this fails.

**Comment by andrewstevenson** [comment]
@sundipnair this is a veriin issue in helm, kubectl or AKS. It could be RBAC. Is it enabled on your cluster? You can disable it vis the values.yaml or command line flag

**Comment by sundipnair** [comment]
@andrewstevenson,

I have RBAC enabled on my cluster. I ran 

helm install landoop/lenses --name lenses --namespace lenses-system --set ingress.enabled=true,rbacEnable=false

However same result. 

Disabling RBAC on my cluster is not an option. Any other work around?

Thank you.

**Comment by andrewstevenson** [comment]
@sundipnair i can look later but its k8 version issue rather than the chart. I don't believe we have run it agsinst AKS. Does --debug give and info?

**Comment by sundipnair** [comment]
Does this help?

[debug] Created tunnel using local port: '58402'

[debug] SERVER: "127.0.0.1:58402"

[debug] Original chart version: ""
[debug] Fetched landoop/lenses to C:\Users\XYZ\.helm\cache\archive\lenses-2.1.5.tgz

[debug] CHART PATH: C:\Users\P95048488\.helm\cache\archive\lenses-2.1.5.tgz

---------

Is the failure because I did not override the reference for zookeeper and kafka services?

**Comment by andrewstevenson** [comment]
@sundipnair i will look tommorrow. Its not a chart is its a kubectl/helm version issue. K8 isn't recognizing a resource.

**Comment by sundipnair** [comment]
@andrewstevenson ,

Did u you get a chance to check this out?

**Comment by andrewstevenson** [comment]
@sundipnair I've just ran the helm install against a AKS cluster I just created. No issues. Notice I disable the ingress as don't have a loadbalancer such as traefik deployed in this cluster.  ```kafka-helm-charts|master⚡ ⇒ helm install charts/lenses --name helm-lenses-test --namespace lenses --tiller-namespace lenses --set ingress.enabled=false
NAME:   helm-lenses-test
LAST DEPLOYED: Mon Dec  3 16:59:28 2018
NAMESPACE: lenses
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME              TYPE    DATA  AGE
helm-lenses-test  Opaque  2     1s

==> v1/ConfigMap
NAME              DATA  AGE
helm-lenses-test  0     1s

==> v1/ClusterRole
NAME              AGE
helm-lenses-test  1s

==> v1/ClusterRoleBinding
NAME              AGE
helm-lenses-test  1s

==> v1/Service
NAME              TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)            AGE
helm-lenses-test  ClusterIP  10.0.0.169  <none>       3030/TCP,9102/TCP  1s

==> v1beta1/Deployment
NAME              DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
helm-lenses-test  1        1        1           0          1s

==> v1/Pod(related)
NAME                              READY  STATUS             RESTARTS  AGE
helm-lenses-test-bf7fb45dd-29267  0/1    ContainerCreating  0         0s```

**Comment by sundipnair** [comment]
Oh … tricky.

Created a new cluster and tried to run again. Different result "Error: failed to download "charts/lenses" (hint: running `helm repo update` may help)"

I have run the helm repo add and helm update. 

Let me dig further.

Sundip

**Comment by andrewstevenson** [comment]
@sundipnair I've just come across and issue in the Helm that was missing an ApiVersion tag so didn't deploy on a bare metal k8 install, I dunno why this didn't affect our internal AKS clusters.

There's a PR pending for Lenses 2.2 that addresses this. Can you try it once merged? https://github.com/Landoop/kafka-helm-charts/pull/38

**Comment by sundipnair** [comment]
@andrewstevenson,

Pulled from the latest master branch (2.2). Still does not work on a brand new AKS cluster.

`PS C:\_temp_github\kafka-helm-charts> helm install .\charts\lenses\ --name lenses --namespace lenses
Error: release lenses failed: Ingress.extensions "lenses" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "lenses": must be an absolute path`

Sundip

**Comment by andrewstevenson** [comment]
@sundipnair The chart enables an ingress, you have to set the ingress path otherwise is use the release name, which isn't valid. You can disable the ingress

**Comment by sundipnair** [comment]
@andrewstevenson,

Disabling the ingress worked when I used my local helm chart. I think the ingresspath not being specified was my core issue. Nothing to do with the 2.2 release.

Thank you.
