### ISSUE TITLE
Lenses Connect protocol property missing 

### ISSUE THREAD

**Issue by struthj** [Landoop/kafka-helm-charts#60]
https://github.com/Landoop/kafka-helm-charts/blob/3a5e7472ff5791e6c5eed3574301fbf598b70877/charts/lenses/templates/_helper.tpl#L207

I notice that `protocol` must be defined for connectors as well. This isn't listed in the lenses helm documentation [here](https://docs.lenses.io/2.2/install_setup/deployment-options/kubernetes-deployment.html?highlight=helm%20charts#helm-connect-clusters) for connectors, but it is listed for schema registry. Is there a way for community to contribute to docs to add this?

**Comment by struthj** [comment]
Will ask on the slack channel closing this for now

**Comment by andmarios** [comment]
@spirosoik @andrewstevenson can you please update this part of the docs?

**Comment by spirosoik** [comment]
@struthj we updated the docs. Thanks for mentioning it. I am closing the ticket
