### ISSUE TITLE
Failed to find any class that implements Connector

### ISSUE THREAD

**Issue by drmjbb** [Landoop/kafka-helm-charts#8]
I tried using Influxsink connector and as well as Elasticsink connector in Helm charts and I see the below error ,

Error: the Kafka Connect API returned: Failed to find any class that implements Connector and which name matches com.datamountaineer.streamreactor.connect.elastic5.ElasticSinkConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'} (500) 
done.

This is my config, 

KAFKA_HEAP_OPTS: -Xmx256M
CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
CONNECT_GROUP_ID: elastic
CONNECT_BOOTSTRAP_SERVERS: kafka:9092
CONNECT_REST_PORT: 8083
CONNECT_CONFIG_STORAGE_TOPIC: connect-elastic-configs
CONNECT_OFFSET_STORAGE_TOPIC: connect-elastic-offsets
CONNECT_STATUS_STORAGE_TOPIC: connect-elastic-statuses
CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 
CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 
CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_REST_ADVERTISED_HOST_NAME: 
CONNECT_PLUGIN_PATH: /etc/landoop/jars
CONNECTOR_NAME: elastic-sink-0
CONNECTOR_GROUP_ID: elastic-sink-0
CONNECTOR_CONNECTOR_CLASS: com.datamountaineer.streamreactor.connect.elastic5.ElasticSinkConnector
CONNECTOR_TASKS_MAX: 1
CONNECTOR_CONNECT_ELASTIC_CLUSTER_NAME: elastic
CONNECTOR_CONNECT_ELASTIC_MAX_RETRIES: 20
CONNECTOR_CONNECT_ELASTIC_WRITE_TIMEOUT: 300000
CONNECTOR_CONNECT_ELASTIC_ERROR_POLICY: THROW
CONNECTOR_CONNECT_ELASTIC_XPACK_PLUGINS: 
CONNECTOR_CONNECT_ELASTIC_URL_PREFIX: elasticsearch
CONNECTOR_CONNECT_PROGRESS_ENABLED: true
CONNECTOR_CONNECT_ELASTIC_XPACK_SETTINGS ():
CONNECTOR_CONNECT_ELASTIC_URL: localhost:9300
CONNECTOR_CONNECT_ELASTIC_KCQL: SELECT * FROM data
CONNECTOR_CONNECT_ELASTIC_BATCH_SIZE: 4000
CONNECTOR_CONNECT_ELASTIC_USE_HTTP: tcp

**Comment by fjbsantiago** [comment]
This connector class is available in the docker image:
```
datamountaineer/kafka-connect-elastic5:0.3.0
```
And you must set the plugin.path variable as so:
```
CONNECT_PLUGIN_PATH=/etc/datamountaineer/jars
```

**Comment by andrewstevenson** [comment]
@fjbsantiago they shouldn't be in datamountainer/jars but landoop/jars https://github.com/Landoop/dockers/blob/master/kafka-connect/Dockerfile
Let me check

**Comment by andrewstevenson** [comment]
@fjbsantiago I see the jar?

~|⇒ docker run -ti datamountaineer/kafka-connect-elastic5 /bin/bash
root@601366f9f2a2:/#
root@601366f9f2a2:/# ls -lrt /etc/landoop/jars/lib/
total 113068
-rw-r--r-- 1 61001 61001 115778605 Jan 18 10:34 kafka-connect-elastic5-1.0.0-1.0.0-all.jar
root@601366f9f2a2:/#

**Comment by fjbsantiago** [comment]
@andrewstevenson, you are right. Sorry about that.
I was having the same issue as the OP, but with the image **datamountaineer/kafka-connect-elastic5** version **0.3.0**

I edited my question and removed the version by mistake.

**Comment by andrewstevenson** [comment]
@fjbsantiago No problem, please find any issues you find on the helm charts, they are very much a moving target at the moment to align them with Lenses.

**Comment by Antwnis** [comment]
Closing + tidying this one up - as it seems to have been resolved for a while
