### ISSUE TITLE
Incorrect Repository for connect redis chart?

### ISSUE THREAD

**Issue by Richard-Mathie** [Landoop/kafka-helm-charts#82]
The helm chart for the redis connector refers to image: [`streamreactor/redis-sink`](https://github.com/Landoop/kafka-helm-charts/blob/master/charts/kafka-connect-redis-sink/values.yaml#L6), but on docker hub the only redis image is [`streamreactor/redis`](https://hub.docker.com/r/streamreactor/redis/tags)

see: [charts/kafka-connect-redis-sink/values.yaml#L6](https://github.com/Landoop/kafka-helm-charts/blob/master/charts/kafka-connect-redis-sink/values.yaml#L6)

```yaml
image:
  repository: streamreactor/redis-sink
```

Am i correct in thinking this is a mistake? or should i be pointing to a different set of repositories?

**Comment by spirosoik** [comment]
Hi @Richard-Mathie you are correct, you can use your own `values.yaml` to override this. Meanwhile I will fix this issue.

**Comment by spirosoik** [comment]
Closing, as it will be fixed with the raised PR. Thanks for reporting the issue.
